//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clojure.lang.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("clojure.lang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] clojure_clr_io_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_clr_io_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_clr_shell_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_clr_shell_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_core_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_core_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_core_clr_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_core_clr_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_core_deftype_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_core_deftype_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_core_print_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_core_print_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_core_protocols_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_core_protocols_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_core_proxy_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_core_proxy_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_data_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_data_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_genclass_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_genclass_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_gvec_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_gvec_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_instant_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_instant_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_main_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_main_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_pprint_cl_format_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_pprint_cl_format_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_pprint_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_pprint_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_pprint_column_writer_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_pprint_column_writer_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_pprint_dispatch_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_pprint_dispatch_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_pprint_pprint_base_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_pprint_pprint_base_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_pprint_pretty_writer_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_pprint_pretty_writer_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_pprint_print_table_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_pprint_print_table_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_pprint_utilities_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_pprint_utilities_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_reflect_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_reflect_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_reflect_clr_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_reflect_clr_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_repl_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_repl_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_set_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_set_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_stacktrace_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_stacktrace_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_string_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_string_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_template_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_template_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_test_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_test_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_test_junit_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_test_junit_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_test_tap_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_test_tap_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_uuid_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_uuid_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_walk_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_walk_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] clojure_zip_clj {
            get {
                object obj = ResourceManager.GetObject("clojure_zip_clj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version=1.4.0-master-SNAPSHOT.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
