peverify /verbose clojure.clr.io.clj.dll
peverify /verbose clojure.clr.shell.clj.dll
peverify /verbose clojure.core.clj.dll
peverify /verbose clojure.core.protocols.clj.dll
peverify /verbose clojure.core_clr.clj.dll
peverify /verbose clojure.core_deftype.clj.dll
peverify /verbose clojure.core_print.clj.dll
peverify /verbose clojure.core_proxy.clj.dll
peverify /verbose clojure.data.clj.dll
peverify /verbose clojure.data.generators.dll
peverify /verbose clojure.edn.clj.dll
peverify /verbose clojure.genclass.clj.dll
peverify /verbose clojure.gvec.clj.dll
peverify /verbose clojure.instant.clj.dll
peverify /verbose clojure.main.clj.dll
peverify /verbose clojure.pprint.clj.dll
peverify /verbose clojure.pprint.cl_format.clj.dll
peverify /verbose clojure.pprint.column_writer.clj.dll
peverify /verbose clojure.pprint.dispatch.clj.dll
peverify /verbose clojure.pprint.pprint_base.clj.dll
peverify /verbose clojure.pprint.pretty_writer.clj.dll
peverify /verbose clojure.pprint.print_table.clj.dll
peverify /verbose clojure.pprint.utilities.clj.dll
peverify /verbose clojure.reflect.clj.dll
peverify /verbose clojure.reflect.clr.clj.dll
peverify /verbose clojure.repl.clj.dll
peverify /verbose clojure.set.clj.dll
peverify /verbose clojure.stacktrace.clj.dll
peverify /verbose clojure.string.clj.dll
peverify /verbose clojure.template.clj.dll
peverify /verbose clojure.test.check.dll
peverify /verbose clojure.test.clj.dll
peverify /verbose clojure.test.generative.dll
peverify /verbose clojure.test.junit.clj.dll
peverify /verbose clojure.test.tap.clj.dll
peverify /verbose clojure.test_clojure.attributes.clj.dll
peverify /verbose clojure.test_clojure.genclass.examples.clj.dll
peverify /verbose clojure.test_clojure.genclass.examples.ExampleClass.dll
peverify /verbose clojure.test_clojure.protocols.examples.clj.dll
peverify /verbose clojure.tools.namespace.dll
peverify /verbose clojure.uuid.clj.dll
peverify /verbose clojure.walk.clj.dll
peverify /verbose clojure.zip.clj.dll