//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clojure.Source.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clojure.Source.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;   Copyright (c) Rich Hickey. All rights reserved.
        ///;   The use and distribution terms for this software are covered by the
        ///;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
        ///;   which can be found in the file epl-v10.html at the root of this distribution.
        ///;   By using this software in any fashion, you are agreeing to be bound by
        ///;   the terms of this license.
        ///;   You must not remove this notice, or any other, from this software.
        ///
        ///(ns ^{:doc &quot;The core Clojure language.&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string core {
            get {
                return ResourceManager.GetString("core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;   Copyright (c) Rich Hickey. All rights reserved.
        ///;   The use and distribution terms for this software are covered by the
        ///;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
        ///;   which can be found in the file epl-v10.html at the root of this distribution.
        ///;   By using this software in any fashion, you are agreeing to be bound by
        ///;   the terms of this license.
        ///;   You must not remove this notice, or any other, from this software.
        ///
        ///(in-ns &apos;clojure.core)
        ///
        ///;;;;;;;;;;;;;;; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string core_print {
            get {
                return ResourceManager.GetString("core_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;; Copyright (c) Rich Hickey All rights reserved. The use and
        ///;; distribution terms for this software are covered by the Eclipse Public
        ///;; License 1.0 (http://opensource.org/licenses/eclipse-1.0.php) which can be found
        ///;; in the file epl-v10.html at the root of this distribution. By using this
        ///;; software in any fashion, you are agreeing to be bound by the terms of
        ///;; this license. You must not remove this notice, or any other, from this
        ///;; software.
        ///
        ///;; Originally contributed by Stephen C. Gilardi
        ///
        ///(ns ^{: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;   Copyright (c) Rich Hickey. All rights reserved.
        ///;   The use and distribution terms for this software are covered by the
        ///;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
        ///;   which can be found in the file epl-v10.html at the root of this distribution.
        ///;   By using this software in any fashion, you are agreeing to be bound by
        ///;   the terms of this license.
        ///;   You must not remove this notice, or any other, from this software.
        ///
        ///(ns ^{:doc &quot;Set operations such as union/interse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;   Copyright (c) Rich Hickey. All rights reserved.
        ///;   The use and distribution terms for this software are covered by the
        ///;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
        ///;   which can be found in the file epl-v10.html at the root of this distribution.
        ///;   By using this software in any fashion, you are agreeing to be bound by
        ///;   the terms of this license.
        ///;   You must not remove this notice, or any other, from this software.
        ///
        ///;;; stacktrace.clj: print Clojure-centric stack  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stacktrace {
            get {
                return ResourceManager.GetString("stacktrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;   Copyright (c) Rich Hickey. All rights reserved.
        ///;   The use and distribution terms for this software are covered by the
        ///;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
        ///;   which can be found in the file epl-v10.html at the root of this distribution.
        ///;   By using this software in any fashion, you are agreeing to be bound by
        ///;   the terms of this license.
        ///;   You must not remove this notice, or any other, from this software.
        ///
        ///;;; test_is/tap.clj: Extension to test for TAP o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tap {
            get {
                return ResourceManager.GetString("tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;   Copyright (c) Rich Hickey. All rights reserved.
        ///;   The use and distribution terms for this software are covered by the
        ///;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
        ///;   which can be found in the file epl-v10.html at the root of this distribution.
        ///;   By using this software in any fashion, you are agreeing to be bound by
        ///;   the terms of this license.
        ///;   You must not remove this notice, or any other, from this software.
        ///
        ///;;; template.clj - anonymous functions that pre- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;   Copyright (c) Rich Hickey. All rights reserved.
        ///;   The use and distribution terms for this software are covered by the
        ///;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
        ///;   which can be found in the file epl-v10.html at the root of this distribution.F
        ///;   By using this software in any fashion, you are agreeing to be bound by
        ///;   the terms of this license.
        ///;   You must not remove this notice, or any other, from this software.
        ///
        ///;;; test.clj: test framework for Clojure
        ///
        ///;; by [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;   Copyright (c) Rich Hickey. All rights reserved.
        ///;   The use and distribution terms for this software are covered by the
        ///;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
        ///;   which can be found in the file epl-v10.html at the root of this distribution.
        ///;   By using this software in any fashion, you are agreeing to be bound by
        ///;   the terms of this license.
        ///;   You must not remove this notice, or any other, from this software.
        ///
        ///;;; walk.clj - generic tree walker with replacem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string walk {
            get {
                return ResourceManager.GetString("walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;   Copyright (c) Rich Hickey. All rights reserved.
        ///;   The use and distribution terms for this software are covered by the
        ///;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
        ///;   which can be found in the file epl-v10.html at the root of this distribution.
        ///;   By using this software in any fashion, you are agreeing to be bound by
        ///;   the terms of this license.
        ///;   You must not remove this notice, or any other, from this software.
        ///
        ///;functional hierarchical zipper, with navigation [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
